### ISSUE TITLE
[Crash] Crashes when rendering item collector box with ImmediatelyFast

### ISSUE THREAD

**Issue by amyavi** [SuperMartijn642/ItemCollectors#35]
**Version Info**
- Minecraft, 1.20.1 (Fabric)
- Item Collectors, 1.1.10
- ImmediatelyFast, 1.2.18

**Steps to Reproduce**
Theoretically this crash should happen every time you hover over a item collector with IF installed, but I've only managed to get it to happen consistently when rendering AE2's ME Formation Plane.
1. Install AE2, Item Collectors and ImmediatelyFast
2. Look at an item collector while rendering a ME Formation Plane's front side
3. The game crashes

I've also created a small world that should provoke the crash as soon as you hover over the item collector: [test.zip](https://github.com/user-attachments/files/16091901/test.zip).

I believe the crash happens due to the core library's RenderUtils class [utilizing the main BufferSource](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/blob/fabric-1.20/src/main/java/com/supermartijn642/core/render/RenderUtils.java#L111) when rendering boxes and their outlines. To fix this, you'd need to make these functions take a BufferSource and pass `WorldRenderContext#consumers()` to them in [onBlockHighlight](https://github.com/SuperMartijn642/ItemCollectors/blob/fabric-1.20/src/main/java/com/supermartijn642/itemcollectors/ItemCollectorsClient.java#L60-L61).

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/user-attachments/files/16091915/latest.log)
[crash-2024-07-03_21.27.34-client.txt](https://github.com/user-attachments/files/16091967/crash-2024-07-03_21.27.34-client.txt)

Relevant exception:
```
java.lang.IllegalStateException: BufferBuilder not started
	at net.minecraft.class_287.method_22900(class_287.java:396) ~[client-intermediary.jar:?]
	at net.minecraft.class_4584.method_22912(class_4584.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_4588.method_22918(class_4588.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3278(class_761.java:2522) ~[client-intermediary.jar:?]
	at net.minecraft.class_265.method_1106(class_265.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_251.method_1052(class_251.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_251.method_1064(class_251.java:129) ~[client-intermediary.jar:?]
	at net.minecraft.class_265.method_1104(class_265.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3291(class_761.java:2513) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22712(class_761.java:2466) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1443) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

**Comment by hideki2k02** [comment]
This issue still persist on the latest version of the mod for 1.20.1

Minecraft: 1.20.1
Fabric Version: 0.19.2
Item Collectors: 1.1.12
ImmediatelyFast: 1.5.4

**Comment by SuperMartijn642** [comment]
This should be fixed with the newest version of Fabric API for 1.20.1, 0.92.12+1.20.1.
